version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /Users/chitranshi/projects/learn/datacli/db
    hostname: mongoclient
    depends_on:
      - mongodb
    ports:
      - 3300:3000