spring:
  application:
    name: todos-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/todos-identity-manager

  data:
    mongodb:
      host: localhost
      port: 27017
      database: todos
      auto-index-creation: true

server:
  port: 7070

idm:
  audience: account

logging:
  level:
    root: debug